### PR TITLE
KIALI-1766 - Using Swagger to generate Kiali Client

### PR DESCRIPTION
**Pull request by gbaufake**
Using Swagger to auto-generate the Files and including Requests for some Metadata on Requests

### CODE REVIEW

**Comment by gbaufake** [comment]
This Pull Request included 33 API Tests (one for each REST API available at swagger)

**Comment by mattmahoneyrh** [comment]
Consider adding handling/retries for connection errors that appear to be transient and random, during E2E test runs.

**Comment by burmanm** [comment]
Shouldn't the E2E test take care of that? If there's a connection error, you'll get a Python error which can be easily catched.

I don't know why this copy of client removed the error handling, but this is the part from Hawkular's codebase:

```python
        elif isinstance(e, URLError):
            # Cast to HawkularMetricsConnectionError
            ee = HawkularConnectionError(e)
            ee.msg = "Error, could not send event(s) to the Hawkular Metrics: " + str(e.reason)
            raise ee
```

Those are the cases when there's a connection timeout etc.

**Comment by gbaufake** [comment]
> Shouldn't the E2E test take care of that? If there's a connection error, you'll get a Python error which can be easily catched.
> 
> I don't know why this copy of client removed the error handling, but this is the part from Hawkular's codebase:
> 
> ```python
>         elif isinstance(e, URLError):
>             # Cast to HawkularMetricsConnectionError
>             ee = HawkularConnectionError(e)
>             ee.msg = "Error, could not send event(s) to the Hawkular Metrics: " + str(e.reason)
>             raise ee
> ```
> 
> Those are the cases when there's a connection timeout etc.

I have removed on this PR because we wanted to know more than error message... eg: request, url and other metadata that might be useful to discover if the test failed because of an environmental issue or some problem on API.

Maybe I could implement an error handling that can have another.
Any suggestion on this @burmanm?

**Comment by burmanm** [comment]
Why would those casts remove the access to that information? They were just using inheritance, ``class HawkularConnectionError(URLError):``. The idea was to make the client hide certain implementation details in everyday use. 

Point is, I think retry should be in the testing code - not the client code. Otherwise the client's retry might hide something that should be catched by tests. The test should determine which failures are acceptable, not the client. That's my opinion.

**Comment by gbaufake** [comment]
This PR depends on https://github.com/kiali/kiali/pull/693 and https://github.com/kiali/kiali/pull/698

**Pull request merged**
